[mypy]
plugins = mypy_django_plugin.main
strict = True
ignore_missing_imports = True
exclude = env|venv|\.env|\.venv|migrations

[mypy.plugins.django-stubs]
django_settings_module = "MyHomeDjango.settings"
