# Generated by Django 3.2.18 on 2023-05-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('LIGHT_RESERVE_PK', models.IntegerField(primary_key=True, serialize=False, verbose_name='LIGHT_RESERVE_PK')),
                ('NAME_CHAR', models.CharField(max_length=32)),
                ('NAMEKOR_CHAR', models.CharField(max_length=32)),
                ('TIME_CHAR', models.CharField(max_length=32)),
                ('ROOM_CHAR', models.CharField(max_length=32)),
                ('DO_CHAR', models.CharField(max_length=16)),
                ('DAY_CHAR', models.CharField(max_length=25)),
                ('ACTIVATED_CHAR', models.CharField(max_length=20)),
                ('REITERATION_CHAR', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'LIGHT_RESERVE_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomLight',
            fields=[
                ('LIGHT_ROOM_PK', models.CharField(max_length=20, primary_key=True)),
                ('STATE_CHAR', models.CharField(max_length=10)),
                ('ROOMKOR_CHAR', models.CharField(max_length=20)),
                ('CATEGORY_CHAR', models.CharField(max_length=100)),
                ('CONNECT_CHAR', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'LIGHT_ROOM_TB',
                'managed': False,
            },
        ),
    ]
