# Generated by Django 3.2.18 on 2023-05-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=32)),
                ('NAMEKOR_CHAR', models.CharField(max_length=32)),
                ('time', models.CharField(max_length=32)),
                ('room', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=16)),
                ('day', models.CharField(max_length=25)),
                ('activated', models.CharField(max_length=20)),
                ('reiteration', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'LIGHT_RESERVE_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomLight',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True)),
                ('state', models.CharField(max_length=10)),
                ('room_kor', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('connect_status', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'LIGHT_ROOM_TB',
                'managed': False,
            },
        ),
    ]
