# Generated by Django 3.2.18 on 2023-05-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightRecord',
            fields=[
                ('LIGHT_RECORD_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('DAY_CHAR', models.CharField(max_length=32)),
                ('TIME_CHAR', models.CharField(max_length=32)),
                ('ROOM_CHAR', models.CharField(max_length=64)),
                ('DO_CHAR', models.CharField(max_length=16)),
                ('USER_CHAR', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'LIGHT_RECORD_TB',
                'managed': False,
            },
        ),
    ]
